Vagrant.configure("2") do |config|
	config.vm.box = "generic/debian12"
	config.vm.box_version = "4.3.12"

	config.vm.synced_folder ".", "/vagrant"

	config.vm.define "lomontS" do |server|
		server.vm.hostname = "lomontS"
		server.vm.network "private_network", ip: "192.168.56.110"

		server.vm.provider "virtualbox" do |v|
			v.memory = 2048
			v.cpus = 2
			v.name = "lomontS"
		end

		server.vm.provision "shell", path: "scripts/install-dependencies.sh"
		server.vm.provision "shell", path: "scripts/change-html.sh", privileged: true
	end
end
