Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine318"
	config.vm.box_version = "4.3.12"
	config.vm.box_architecture = "amd64"
	config.vm.synced_folder "./", "/mnt"

	config.vm.provider "virtualbox" do |v|
		v.memory = 1536
		v.cpus = 1
		v.customize ["modifyvm", :id, "--name", "lomontS"]
		v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
		v.customize ["modifyvm", :id, "--vtxux", "on"]
		v.customize ["modifyvm", :id, "--vtxvpid", "on"]
	end

	config.vm.define "lomontS" do |control|
		control.vm.hostname = "lomontS"
		control.vm.network "private_network", ip: "192.168.56.110", netmask: "255.255.255.0"
		control.vm.provision "shell", path: "./scripts/install-dependencies.sh"
	end
end
