Vagrant.configure("2") do |config|
	config.vm.box = "takesako/alpine-standard-v3.18"
	config.vm.box_version = "3.18.5"
	config.vm.box_architecture = "amd64"
	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.provider "virtualbox" do |v|
		v.memory = 1536
		v.cpus = 1
		v.customize ["modifyvm", :id, "--name", "lomontS"]
	end

	config.vm.provider "vmware_desktop" do |v|
		v.vmx["memsize"] = "1536"
		v.vmx["numvcpus"] = "1"
		v.vmx["displayName"] = "lomontS"
	end

	config.vm.define "lomontS" do |control|
		control.vm.hostname = "lomontS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provision "shell", path: "./scripts/install-dependencies.sh"
		control.vm.provision "shell", privileged: true, path: "./scripts/change-html.sh"
	end
end
