Vagrant.configure("2") do |config|
	config.vm.box = "takesako/alpine-standard-v3.18"
	config.vm.box_version = "3.18.5"

	config.vm.define "lomontS" do |server|
		server.vm.hostname = "lomontS"
		server.vm.network "private_network", ip: "192.168.56.110"

		server.vm.provision "shell", name: "install-dependencies", path: "scripts/s_install-dependencies.sh"

		server.vm.provider "virtualbox" do |v|
			v.memory = 2048
			v.cpus = 2
			v.customize ["modifyvm", :id, "--name", "lomontS"]
		end

		server.vm.provider "vmware_desktop" do |v|
			v.memory = 2048
			v.cpus = 2
			v.vmx["displayname"] = "lomontS"
		end
	end

	config.vm.define "lomontSW" do |worker|
		worker.vm.hostname = "lomontSW"
		worker.vm.network "private_network", ip: "192.168.56.111"

		worker.vm.provision "shell", name: "install-dependencies", path: "scripts/sw_install-dependencies.sh"

		worker.vm.provider "virtualbox" do |v|
			v.memory = 512
			v.cpus = 1
			v.customize ["modifyvm", :id, "--name", "lomontSW"]
		end

		worker.vm.provider "vmware_desktop" do |v|
			v.memory = 512
			v.cpus = 1
			v.vmx["displayname"] = "lomontSW"
		end
	end
end
